[2024-10-03T22:14:43.111-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T22:14:46.252-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:11:57.983833+00:00 [queued]>
[2024-10-03T22:14:46.493-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:11:57.983833+00:00 [queued]>
[2024-10-03T22:14:46.495-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-03T22:14:46.831-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): upload_pdfs_task> on 2024-10-04 02:11:57.983833+00:00
[2024-10-03T22:14:46.835-0400] {standard_task_runner.py:72} INFO - Started process 24782 to run task
[2024-10-03T22:14:46.837-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'huggingface_pdf_pipeline', 'upload_pdfs_task', 'manual__2024-10-04T02:11:57.983833+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/huggingface_pdf_airflow_dag.py', '--cfg-path', '/tmp/tmpkkl8ppul']
[2024-10-03T22:14:46.838-0400] {standard_task_runner.py:105} INFO - Job 28: Subtask upload_pdfs_task
[2024-10-03T22:14:55.344-0400] {job.py:229} INFO - Heartbeat recovered after 29.02 seconds
[2024-10-03T22:14:56.545-0400] {task_command.py:467} INFO - Running <TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:11:57.983833+00:00 [running]> on host LAPTOP-GD5THE3N.
[2024-10-03T22:15:17.597-0400] {job.py:229} INFO - Heartbeat recovered after 22.36 seconds
[2024-10-03T22:15:27.103-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='huggingface_pdf_pipeline' AIRFLOW_CTX_TASK_ID='upload_pdfs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T02:11:57.983833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T02:11:57.983833+00:00'
[2024-10-03T22:15:27.107-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-03T22:15:27.110-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-03T22:15:27.112-0400] {logging_mixin.py:190} INFO - Current task name:upload_pdfs_task state:running start_date:2024-10-04 02:14:46.253016+00:00
[2024-10-03T22:15:27.116-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline and current dag run status:running
[2024-10-03T22:15:27.117-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T22:15:27.120-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:15:27.123-0400] {logging_mixin.py:190} INFO - Error uploading h to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'h'
[2024-10-03T22:15:27.125-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:15:27.126-0400] {logging_mixin.py:190} INFO - Error uploading m to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'm'
[2024-10-03T22:15:27.128-0400] {logging_mixin.py:190} INFO - Error uploading e to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'e'
[2024-10-03T22:15:27.129-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:15:27.130-0400] {logging_mixin.py:190} INFO - Error uploading p to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'p'
[2024-10-03T22:15:27.130-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T22:15:27.131-0400] {logging_mixin.py:190} INFO - Error uploading t to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 't'
[2024-10-03T22:15:27.132-0400] {logging_mixin.py:190} INFO - Error uploading r to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'r'
[2024-10-03T22:15:27.133-0400] {logging_mixin.py:190} INFO - Error uploading i to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'i'
[2024-10-03T22:15:27.134-0400] {logging_mixin.py:190} INFO - Error uploading c to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'c'
[2024-10-03T22:15:27.134-0400] {logging_mixin.py:190} INFO - Error uploading k to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'k'
[2024-10-03T22:15:27.135-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:15:27.136-0400] {logging_mixin.py:190} INFO - Error uploading D to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'D'
[2024-10-03T22:15:27.137-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:15:27.138-0400] {logging_mixin.py:190} INFO - Error uploading w to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'w'
[2024-10-03T22:15:27.138-0400] {logging_mixin.py:190} INFO - Error uploading n to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'n'
[2024-10-03T22:15:27.139-0400] {logging_mixin.py:190} INFO - Error uploading l to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'l'
[2024-10-03T22:15:27.140-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:15:27.141-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T22:15:27.141-0400] {logging_mixin.py:190} INFO - Error uploading d to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'd'
[2024-10-03T22:15:27.143-0400] {logging_mixin.py:190} INFO - Error uploading s to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 's'
[2024-10-03T22:15:27.143-0400] {python.py:240} INFO - Done. Returned value was: None
[2024-10-03T22:15:35.751-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T22:15:35.754-0400] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=huggingface_pdf_pipeline, task_id=upload_pdfs_task, run_id=manual__2024-10-04T02:11:57.983833+00:00, execution_date=20241004T021157, start_date=20241004T021446, end_date=20241004T021535
[2024-10-03T22:15:35.973-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-03T22:15:35.977-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-03T22:15:35.979-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline queued_at:2024-10-04 02:11:58.460142+00:00
[2024-10-03T22:15:35.981-0400] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-GD5THE3N. operator:PythonOperator
[2024-10-03T22:15:37.492-0400] {job.py:229} INFO - Heartbeat recovered after 20.00 seconds
[2024-10-03T22:15:39.528-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-03T22:15:41.899-0400] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-03T22:15:43.808-0400] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-03T22:15:43.858-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
